version: "1"
services:
  psql:
    image: postgres:alpine3.17
    ports:
      - "35432:5432"
    volumes:
      - ./psql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - tmp:/tmp
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  api:
    build: ./api/
    depends_on:
      - psql
      - mongo
    ports:
      - "3000:3000"
      - "3001:3001"
    command: sh -c "./migrate.sh && npm run dev"
    environment:
      POSTGRESQL_URL: postgresql://user:pass@psql:5432/db
      MONGO_URL: mongodb://@mongo:27017/facturacion?directConnection=true
    volumes:
      - ./api/:/app/
      - /app/node_modules
      - tmp:/tmp
volumes:
    tmp: 
    
  